language: java
sudo: false
install: true
jdk: oraclejdk8
script: ./travis.sh

env:
  - TARGET=CI

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar
    - server/sonar-web/node
    - server/sonar-web/node_modules
    - $HOME/jvm
    - $HOME/phantomjs

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/org/sonarsource/sonarqube
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
  email: false
  webhooks:
    - secure: "lr4XnJTi/hnRMa8JSyHsqBLY4cHRn2+Cm1ndylinyy90lZ6GgFOaiFfDNlKwGR1BePkCvhr6WEtRb6q+cCthKQhxXriwZGge2VBcpiFHODfX8rJAg9E6E3m+IW3fXZYDmMKAa/4mIeCeySEsv/f3ihBVs+YZ/z7CV29Aq5prJ6wMsHaTJGr1DhxxqWpN+8j1KOx6VcFRjckHVtU8+qStMk+LiTH3BJe6uHbzp9W5/5w0cECkhTbp3Nj5jU77/rzy6r2DRkGmZAYFgF5wHt6NvqCd0z+Pj5BvJkE43lNvpWL7V0bySyY3vHEeUZX+pdjqeZd+jq9WVwV1tVz7VzHWnOTctH3H+Y27TrcdPapJab8f4CLtbKS3D6sjk9rokOAX1npxvybLVJDAFdv97TiWRRHCQVaZLN2SksyN23RscahBtu5e8WsGRyLqY0UhaIvD7IhRfL8WWZmmwB7FksR7nVqFPcs+QddisHSMqJSSer7Y5epfDqMzOpmrzqB1BqugzoBBMtf3Kn+pYPnrMv7Np8KzhPSzAnHzrXUOmpnOsZd3P4H2Fd+m/+pxBalUXTcuibDOyK/2k5nKszi8/3QoGclMZ1FjId2SuV1EWXVWkRs4pD+4x/7zLw6sSw9bLoVFVhIxBCThcEBZylu6PLXy1ZTNHxOfTT8qywydHgtbGSQ="
  on_success: always
  on_failure: never
  on_start: never
  on_cancel: never
  on_error: never
