language: java
sudo: false
install: true
jdk: oraclejdk8
script: ./travis.sh

env:
  - TARGET=CI

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar
    - server/sonar-web/node
    - server/sonar-web/node_modules
    - $HOME/jvm
    - $HOME/phantomjs

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/org/sonarsource/sonarqube
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
  email: false
  webhooks:
    - secure: "oM5hzEposuzK1WUOHc9E6fvPrR73AwcjSJZduJ/T0LWS9j1ZXyqhwMC+xz+BYOVW/rCF56xecLHpNbRqcTvezJd0rCG0DdMdqwLgSR7fgeqnnBdHWZ8NaFDAyR3rGTnhIfojQpWGfQLGTI0gj0J5BhYKIIL06oLyWf0mbRCFXbRrcCLUYRyvE2Y2yNZ0T2rwi20J1UQSwfAsHFHwdag+lSrPAs+k08ODud6MKkhXzFcCtm/t6VG4FLV72Jb5/LHt5BWdPnzVzR8RyJdvVkwhAH7l3ybKjbo3LnpId63prKL9oXO4gOVvBToqrB1uDmIKnIWe72HHJg8OceP3KrkeEOXGfBItiEfk18IlR8d2X3icHmFLVnyHjMkb5xRvrXdo+/texs0AIdZcqijkI1ho+9iJ5WhNUOxo/77temGf6UEhMn3gz/rdD/U4Nm2uiR3IouvRKi7ug5DGCCsNrkqbkBVzprr8pUhRYgJP8L9EKcDpJ47VkUt+/OpmD4oTYEUdl/06HrmOl1PmeMImZTgqqAsVOKP8IhoDDcTcR2PeT1D9u9cjV25dP9q7aa7jn91qWdmgXsJ85b+2wX42xb4/KaMPNwT72MQf/ueBCFgYDxtQXP+5MFESZ39NhV2hyuZtDtQQ9aoQbzs1Lx9tdeLit+RKSbHEVcpkhdCTeYVpCp4="
  on_success: always
  on_failure: never
  on_start: never
  on_cancel: never
  on_error: never
